### ISSUE TITLE
S7 Son Of Graktar spawns on the recall list, not the map

### ISSUE THREAD

**Issue by stevecotton** [CelticMinstrel/BlackCrossOfAleron#1]
I've reached the Dread Marsh with `killedgragchak=yes`. The event that replaces Graktar with his son doesn't include `x,y=` or `placement=` in the `[unit]` tag, so the son is put on side 3's recall list.

Easy fix:
```
                                        name=_"Gashak"
                                        id=sonofgragchak
+                                       placement="leader"
                                        [modifications]
                                                {TRAIT_STRONG}
```

**Comment by CelticMinstrel** [comment]
I've done that several times now... defaulting to recall list is a _very_ surprising behaviour. :(
